version: 2

models:
  - name: int_customers_cleaned
    description: "Intermediate: Deduplicated and cleaned customer data with Brazilian text normalization"
    columns:
      - name: customer_id
        description: "Master customer identifier after deduplication"
        tests:
          - not_null
          - unique
      - name: customer_unique_id
        description: "Original unique customer identifier"
        tests:
          - not_null
      - name: is_master_customer
        description: "Flag indicating master record in deduplication"
        tests:
          - not_null

  - name: int_geolocation_consolidated
    description: "Intermediate: Consolidated geolocation data with optimized coordinates and missing data estimation"
    columns:
      - name: geolocation_zip_code_prefix
        description: "ZIP code prefix"
        tests:
          - not_null
      - name: geolocation_lat_consolidated
        description: "Consolidated latitude coordinate"
        tests:
          - not_null
      - name: geolocation_lng_consolidated
        description: "Consolidated longitude coordinate"  
        tests:
          - not_null

  - name: int_orders_enriched
    description: "Intermediate: Order data with lifecycle analytics and temporal validation"
    columns:
      - name: order_id
        description: "Primary order identifier"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "Customer identifier"
        tests:
          - not_null
      - name: order_status_clean
        description: "Standardized order status"
        tests:
          - not_null

  - name: int_payments_cleaned
    description: "Intermediate: Payment data with validation and edge case handling"
    columns:
      - name: order_id
        description: "Order identifier"
        tests:
          - not_null
      - name: payment_sequential
        description: "Payment sequence number"
        tests:
          - not_null
      - name: payment_value_corrected
        description: "Validated payment value"
        tests:
          - not_null

  - name: int_products_cleaned
    description: "Intermediate: Product data with category normalization and validation"
    columns:
      - name: product_id
        description: "Primary product identifier"
        tests:
          - not_null
          - unique
      - name: product_category_name_clean
        description: "Cleaned category name"
        tests:
          - not_null

  - name: int_products_enriched
    description: "Intermediate: Enhanced product data with analytics attributes"
    columns:
      - name: product_id
        description: "Primary product identifier"
        tests:
          - not_null
          - unique
      - name: product_category_enhanced
        description: "Enhanced category with analytics"
        tests:
          - not_null

  - name: int_sellers_cleaned
    description: "Intermediate: Seller data with Brazilian text normalization"
    columns:
      - name: seller_id
        description: "Primary seller identifier"
        tests:
          - not_null
          - unique
      - name: seller_state_normalized
        description: "Normalized state name"
        tests:
          - not_null
