version: 2

models:
  - name: data_profiling_summary
    description: "Data profiling summary across all tables"
    columns:
      - name: table_name
        description: "Name of the profiled table"
        tests:
          - not_null
      - name: row_count
        description: "Total rows in table"
        tests:
          - not_null
      - name: column_count
        description: "Total columns in table"
        tests:
          - not_null
