
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'olist_data_quality'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'olist_data_quality'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  olist_data_quality:
    # Staging models - raw data with minimal transformations
    staging:
      +materialized: view
      +schema: staging
    
    # Intermediate models - cleaning and business logic
    intermediate:
      +materialized: view
      +schema: intermediate
    
    # Data quality models - monitoring and validation
    data_quality:
      +materialized: table
      +schema: data_quality
    
    # Marts models - final clean datasets
    marts:
      +materialized: table
      +schema: marts

# Test configurations
tests:
  +store_failures: true
  +severity: warn
